// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmlnzfodeubthlhjahpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbG56Zm9kZXVidGhsaGphaHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODcyMDYsImV4cCI6MjA2NDc2MzIwNn0.hA08iqzc6BL3e1cStec5x1h6tZmdLJmH34xGS93WEkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);